

export const DELETE_ORDER_INGREDIENT = "DELETE_ORDER_INGREDIENT";
export const MOVE_ORDER_INGREDIENT = "MOVE_ORDER_INGREDIENT";

export const ADD_ORDER_BUN = "ADD_ORDER_BUN";
export const ADD_ORDER_INGREDIENT = "ADD_ORDER_INGREDIENT";


