export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
export const GET_AUTH_FAILURE = "GET_AUTH_FAILURE";

export const GET_FORGOT_REQUEST = "GET_FORGOT_REQUEST";
export const GET_FORGOT_SUCCESS: "GET_FORGOT_SUCCESS" = "GET_FORGOT_SUCCESS";
export const GET_FORGOT_FAILURE: "GET_FORGOT_FAILURE" = "GET_FORGOT_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_RESET_REQUEST = "GET_RESET_REQUEST";
export const GET_RESET_SUCCESS = "GET_RESET_SUCCESS";
export const GET_RESET_FAILURE = "GET_RESET_FAILURE";

export const GET_REGISTER_REQUEST = "GET_REGISTER_REQUEST";
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS";
export const GET_REGISTER_FAILURE = "GET_REGISTER_FAILURE";

export const GET_UPDATE_REQUEST = "GET_UPDATE_REQUEST";
export const GET_UPDATE_SUCCESS = "GET_UPDATE_SUCCESS";
export const GET_UPDATE_FAILURE = "GET_UPDATE_FAILURE";

export const GET_LOGOUT_REQUEST = "GET_LOGOUT_REQUEST";
export const GET_LOGOUT_SUCCESS = "GET_LOGOUT_SUCCESS";
export const GET_LOGOUT_FAILURE = "GET_LOGOUT_FAILURE";

export const GET_REFRESH_TOKEN_REQUEST = "GET_REFRESH_TOKEN_REQUEST";
export const GET_REFRESH_TOKEN_SUCCESS = "GET_REFRESH_TOKEN_SUCCESS";
export const GET_REFRESH_TOKEN_FAILURE = "GET_REFRESH_TOKEN_FAILURE";

export const CLEAR_USER = "CLEAR_USER";
