// wsActionTypes.ts

export const WS_FEED_CONNECTION_START: "WS_FEED_CONNECTION_START" = "WS_FEED_CONNECTION_START";
export const WS_FEED_CONNECTION_SUCCESS: "WS_FEED_CONNECTION_SUCCESS" = "WS_FEED_CONNECTION_SUCCESS";
export const WS_FEED_CONNECTION_ERROR: "WS_FEED_CONNECTION_ERROR" = "WS_FEED_CONNECTION_ERROR";
export const WS_FEED_CONNECTION_CLOSE: "WS_FEED_CONNECTION_CLOSE" = "WS_FEED_CONNECTION_CLOSE";
export const WS_FEED_CONNECTION_CLOSED: "WS_FEED_CONNECTION_CLOSED" = "WS_FEED_CONNECTION_CLOSED";
export const WS_FEED_GET_MESSAGE: "WS_FEED_GET_MESSAGE" = "WS_FEED_GET_MESSAGE";
export const WS_FEED_SEND_MESSAGE: "WS_FEED_SEND_MESSAGE" = "WS_FEED_SEND_MESSAGE";

export const feedActions = {
  wsStart: WS_FEED_CONNECTION_START,
  wsSuccess: WS_FEED_CONNECTION_SUCCESS,
  wsError: WS_FEED_CONNECTION_ERROR,
  wsClose: WS_FEED_CONNECTION_CLOSE,
  wsClosed: WS_FEED_CONNECTION_CLOSED,
  wsGetMessage: WS_FEED_GET_MESSAGE,
  wsSendMessage: WS_FEED_SEND_MESSAGE,
};


