export const SET_ORDER_REQUEST = "SET_ORDER_REQUEST";
export const SET_ORDER_SUCCES = "SET_ORDER_SUCCES";
export const SET_ORDER_FAILURE = "SET_ORDER_FAILURE";
export const CLEAR_ORDER = "CLEAR_ORDER";
