export const SET_ORDER_REQUEST = "SET_ORDER_REQUEST";
export const SET_ORDER_SUCCES = "SET_ORDER_SUCCES";
export const SET_ORDER_FAILURE = "SET_ORDER_FAILURE";

export const CLEAR_ORDER = "CLEAR_ORDER";
export const SET_CURRENT_ORDER = "SET_CURRENT_ORDER";
export const CLEAR_CURRENT_ORDER = "CLEAR_CURRENT_ORDER";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCES = "GET_ORDER_SUCCES";
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE";
