// wsActionTypes.ts

export const WS_ORDERS_CONNECTION_START: "WS_ORDERS_CONNECTION_START" = "WS_ORDERS_CONNECTION_START";
export const WS_ORDERS_CONNECTION_SUCCESS: "WS_ORDERS_CONNECTION_SUCCESS" = "WS_ORDERS_CONNECTION_SUCCESS";
export const WS_ORDERS_CONNECTION_ERROR: "WS_ORDERS_CONNECTION_ERROR" = "WS_ORDERS_CONNECTION_ERROR";
export const WS_ORDERS_CONNECTION_CLOSE: "WS_ORDERS_CONNECTION_CLOSE" = "WS_ORDERS_CONNECTION_CLOSE";
export const WS_ORDERS_CONNECTION_CLOSED: "WS_ORDERS_CONNECTION_CLOSED" = "WS_ORDERS_CONNECTION_CLOSED";
export const WS_ORDERS_GET_MESSAGE: "WS_ORDERS_GET_MESSAGE" = "WS_ORDERS_GET_MESSAGE";
export const WS_ORDERS_SEND_MESSAGE: "WS_ORDERS_SEND_MESSAGE" = "WS_ORDERS_SEND_MESSAGE";

export const ordersActions = {
  wsStart: WS_ORDERS_CONNECTION_START,
  wsSuccess: WS_ORDERS_CONNECTION_SUCCESS,
  wsError: WS_ORDERS_CONNECTION_ERROR,
  wsClose: WS_ORDERS_CONNECTION_CLOSE,
  wsClosed: WS_ORDERS_CONNECTION_CLOSED,
  wsGetMessage: WS_ORDERS_GET_MESSAGE,
  wsSendMessage: WS_ORDERS_SEND_MESSAGE,
};
